### ISSUE TITLE
conflicting type names from different files

### ISSUE THREAD

**Issue by PAStheLoD** [YousefED/typescript-json-schema#112]
Hello,

We just ran into this "[TODO](https://github.com/YousefED/typescript-json-schema/blob/cf275f3e7c4280ab0b67aa985ea44a0f52d54c19/typescript-json-schema.ts#L825)" (and of course into the typescript version upgrade issue too, we used `object` and that was not recognized).

What'd be the best way to fix the conflicting names? For a quick workaround removing that replace helps. Then symbol names become `"/home/some/thing/path/to/the/module".Whatever`, without the `.ts` at the end of the file path.

**Comment by 5ebastianMeier** [comment]
I just ran into this as well - we encountered a name conflict (and have quite a large modular application)

@domoritz I would like to fix this - can you give me a hint on what the best approach to this would be? I'd say we only have to attach the fully qualified name on the appropriate object or use that name instead of the pure symbol name wherever the retrieval currently fails.

I'm not too familiar yet where that point is, any idea?
