### ISSUE TITLE
TypeScript 2.4 string enums

### ISSUE THREAD

**Issue by benny-medflyt** [YousefED/typescript-json-schema#128]
TypeScript 2.4 will have string enums:
https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#string-enums

Any plans to support this?

thank you

**Comment by domoritz** [comment]
What errors are you getting?

I'm focusing on adding all the latest features to https://github.com/vega/typescript-to-json-schema but I'm happy to review pull requests.

**Comment by benny-medflyt** [comment]
1. I haven't actually tried yet to use typescript 2.4 and string enums with typescript-json-schema 😮 . I will give it a whirl soon when I have some time and report back.

2. Is https://github.com/vega/typescript-to-json-schema going to be the successor to https://github.com/YousefED/typescript-json-schema ? Which one should new projects use?

thank you

**Comment by domoritz** [comment]
Just added ts 2.4 support to https://github.com/vega/typescript-to-json-schema. 

> Is https://github.com/vega/typescript-to-json-schema going to be the successor to https://github.com/YousefED/typescript-json-schema ? Which one should new projects use?

Maybe, maybe not. I have shifted my attention towards the other one because I needed support for proper aliasing. Howver, I decided not to port a lot of features that exist here. I think both libraries ave their place and hopefully it's easy to switch from one to the other. 

I suggest that you try both and see whether theyr support the features you need and produce clean output for your code.

**Comment by amcdnl** [comment]
@domoritz - any chance of adding TS 2.4 support for this project? I'm wanting to use the string enums too.
