### ISSUE TITLE
interface definition does not generate 'required' property in json-schema

### ISSUE THREAD

**Issue by shawnExplore** [YousefED/typescript-json-schema#4]
With typson, properties of an interface are serialized as 'required' unless they are marked optional.

Given an interface like:
```typescript
interface Foo {
   bar? : number
   baz: string 
}
```
In the resulting json-schema, I'd expect **baz** to be marked _required_  and **bar** not. This is based on my previous experiments with typson. That said, toggling this behavior via a config setting or command line parameter would be nice.

It seems like this implementation is significantly different from typson and I maybe shouldn't assume it's a superset of typson?

**Comment by YousefED** [comment]
Hmm this seems like a valid point, would need to dive into this. I'm not entirely sure because baz can still be null or undefined in an implementing class right? (Need some time to work out the different scenarios)

For now, you should already be able to explicitly mark baz as required:

    /**
    * @TJS-required
    */
    baz: string

Regarding the differences with Typson: TJS is definitely not a direct port, but a (re)implementation of what we needed most. This has resulted in some additional features, but might miss some others. You're welcome to keep posting about features you miss here :)

**Comment by EToreo** [comment]
+1 to required marking.

**Comment by domoritz** [comment]
> I'm not entirely sure because baz can still be null or undefined in an implementing class right?

That's an interesting issue. Typson seems to do the "wrong" thing and output required properties. However, I would guess that some people actually want this behavior and tjs could add a command line option to output required properties.
